// <auto-generated />
using System;
using DAO_ReputationService.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_ReputationService.Migrations
{
    [DbContext(typeof(dao_reputationserv_context))]
    [Migration("20211011133939_reputation_models_adjustment")]
    partial class reputation_models_adjustment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_ReputationService.Models.UserReputation", b =>
                {
                    b.Property<int>("UserReputationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Reputation")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserReputationID");

                    b.ToTable("UserReputations");
                });

            modelBuilder.Entity("DAO_ReputationService.Models.UserReputationHistory", b =>
                {
                    b.Property<int>("UserReputationHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<double>("Input")
                        .HasColumnType("double");

                    b.Property<double>("LastTotal")
                        .HasColumnType("double");

                    b.Property<double>("Output")
                        .HasColumnType("double");

                    b.Property<int>("UserReputationID")
                        .HasColumnType("int");

                    b.HasKey("UserReputationHistoryID");

                    b.ToTable("UserReputationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
