// <auto-generated />
using DAO_ReputationService.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_ReputationService.Migrations
{
    [DbContext(typeof(dao_reputationserv_context))]
    [Migration("20211008090627_Reputation_added")]
    partial class Reputation_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_ReputationService.Models.Reputation", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("itemId");

                    b.ToTable("Reputations");
                });
#pragma warning restore 612, 618
        }
    }
}
