// <auto-generated />
using DAO_VotingEngine.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_VotingEngine.Migrations
{
    [DbContext(typeof(dao_votesdb_context))]
    [Migration("20211008073731_dbinit")]
    partial class dbinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_VotingEngine.Models.FormalVotes", b =>
                {
                    b.Property<int>("FormalVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("FormalVoteId");

                    b.ToTable("FormalVotes");
                });

            modelBuilder.Entity("DAO_VotingEngine.Models.InformalVote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.ToTable("InformalVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
