// <auto-generated />
using System;
using DAO_VotingEngine.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_VotingEngine.Migrations
{
    [DbContext(typeof(dao_votesdb_context))]
    partial class dao_votesdb_contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_VotingEngine.Models.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<double>("Reputation")
                        .HasColumnType("double");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.Property<int>("VoteJobID")
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("DAO_VotingEngine.Models.VoteJob", b =>
                {
                    b.Property<int>("VoteJobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsFormal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("VoteJobID");

                    b.ToTable("VoteJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
