// <auto-generated />
using System;
using DAO_RFPService.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_RFPService.Migrations
{
    [DbContext(typeof(dao_rfpdb_context))]
    [Migration("20211026140903_added_Time_RfpBid_table")]
    partial class added_Time_RfpBid_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_RFPService.Models.Rfp", b =>
                {
                    b.Property<int>("RfpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FormInput")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerRfpBidID")
                        .HasColumnType("int");

                    b.HasKey("RfpID");

                    b.ToTable("Rfps");
                });

            modelBuilder.Entity("DAO_RFPService.Models.RfpBid", b =>
                {
                    b.Property<int>("RfpBidID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("RfpID")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RfpBidID");

                    b.ToTable("RfpBids");
                });
#pragma warning restore 612, 618
        }
    }
}
